# Generated by Django 5.1 on 2024-09-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Banks',
            new_name='UserBank',
        ),
        migrations.AlterField(
            model_name='user',
            name='UserDepartment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserLocation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
